### ISSUE TITLE
server is listening but not getting any requests

### ISSUE THREAD

**Issue by hzakher** [blestan/UltraMachine#1]
Hello,
first of all, thanks for your great work.
secondly, 
I tried your server compiling using fpc3+/laz1.6+ under linux.
I needed to adjust few parts to compile it.
i started the server, and checked with netstat
`netstat -apn | grep tcp | grep LISTEN | grep 9001`
it shows that application is running and listening on 0.0.0.0:9001
however, when i try to run a 'GET' (using insomnia or curl), the server does nothing and i get 404 from nginx.
i am using NGINX as reverse proxy running on the same machine as the server application.

can you please share some more details about your test environment? or give more info about basic setup to successfully run a get/post example?

thank you very much

**Comment by blestan** [comment]
http code 404 means "not found". please note that this means that the server is running end responding... something is wrong with our api key and istallled and controlers... you cannot use a browser to send requests

**Comment by hzakher** [comment]
thanks blestan.
i was able to compile and run it using fpc3 with lazarus under linux (64bit).
i was finally able to make it work,
access to `http://127.0.0.1:9001/v1/myapp/login`
with header `x-api-key ABCDE123456` 

thanks
